#!/usr/bin/env python3
"""Generate a C++ resource-string table for LoadStr from WinSCP's .h ids + .rc text.

WinSCP keeps string ids in source/resource/Texts*.h (`#define NAME number`) and the text in
source/resource/Texts*.rc STRINGTABLEs (`NAME, "text"`). This joins them into id->text so the
ported LoadStr returns real messages instead of "str#NNN" placeholders.
"""
import re, sys, os, glob

res_dir = sys.argv[1]
out_path = sys.argv[2]

# 1) NAME -> id from the headers.
name_to_id = {}
for h in glob.glob(os.path.join(res_dir, "*.h")):
    for line in open(h, encoding="utf-8", errors="replace"):
        m = re.match(r'\s*#define\s+([A-Za-z_]\w*)\s+(\d+)\s*$', line)
        if m:
            name_to_id[m.group(1)] = int(m.group(2))

# 2) NAME -> text from the .rc STRINGTABLEs. Entries look like:  NAME, "text..."
#    The text may contain \" escapes and span concatenated "..." "..." pieces.
id_to_text = {}
str_re = re.compile(r'^\s*([A-Za-z_]\w*)\s*,\s*(".*)$')
def parse_strings(s, start):
    """Read one or more concatenated C string literals beginning at s[start]=='\"'."""
    out = []
    i = start
    n = len(s)
    while i < n:
        while i < n and s[i] in ' \t': i += 1
        if i >= n or s[i] != '"': break
        i += 1
        while i < n:
            c = s[i]
            if c == '\\' and i + 1 < n:
                nx = s[i+1]
                out.append({'n':'\n','t':'\t','r':'\r','"':'"','\\':'\\','0':'\0'}.get(nx, nx))
                i += 2; continue
            if c == '"': i += 1; break
            out.append(c); i += 1
    return ''.join(out)

for rc in glob.glob(os.path.join(res_dir, "*.rc")):
    for line in open(rc, encoding="utf-8", errors="replace"):
        m = str_re.match(line)
        if not m: continue
        name = m.group(1)
        if name not in name_to_id: continue
        text = parse_strings(line, line.index('"', m.start(2) - 1) if False else line.index('"'))
        id_to_text[name_to_id[name]] = text

def cesc(s):
    r = []
    for ch in s:
        o = ord(ch)
        if ch == '"': r.append('\\"')
        elif ch == '\\': r.append('\\\\')
        elif ch == '\n': r.append('\\n')
        elif ch == '\r': r.append('\\r')
        elif ch == '\t': r.append('\\t')
        elif o < 32: r.append('\\x%02x" L"' % o)   # close+reopen so following hex isn't absorbed
        elif o < 127: r.append(ch)
        elif o <= 0xFFFF: r.append('\\u%04x' % o)   # bounded universal-char escape
        else: r.append('\\U%08x' % o)
    return ''.join(r)

with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Generated by native/tools/genstrings.py — WinSCP resource strings (id -> text).\n")
    f.write("// DO NOT EDIT. Regenerate from source/resource/*.{h,rc}.\n")
    f.write('#include "winscp/UnicodeString.h"\n#include <unordered_map>\n\n')
    f.write("const wchar_t * winscp_lookup_resstr(int id)\n{\n")
    f.write("  static const std::unordered_map<int, const wchar_t *> M = {\n")
    for k in sorted(id_to_text):
        f.write('    {%d, L"%s"},\n' % (k, cesc(id_to_text[k])))
    f.write("  };\n  auto it = M.find(id);\n  return it == M.end() ? nullptr : it->second;\n}\n")

print("wrote %d strings -> %s" % (len(id_to_text), out_path))
